# Generated by Django 4.1.1 on 2022-09-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gapp", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingrecord",
            name="isCar",
            field=models.BooleanField(default=False),
        ),
    ]
