# Generated by Django 4.1.1 on 2022-09-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gapp", "0004_alter_parkingrecord_exittime"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carno", models.CharField(max_length=15)),
                ("garage_id", models.BigIntegerField()),
                ("phnno", models.BigIntegerField()),
                ("otp", models.IntegerField()),
            ],
        ),
    ]
