# Generated by Django 4.1.1 on 2022-09-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gapp", "0005_otp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otp",
            name="carno",
        ),
    ]
