# Generated by Django 4.1.1 on 2022-09-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gapp", "0007_otp_carno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="carno",
            field=models.CharField(max_length=15),
        ),
    ]
